[package]
name = "isic-back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isic-front = { path="../isic-front" }
isic-middle = { path="../isic-middle" }
