name: Deploy playground

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy_playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update rust toolchain
        run: |
          rustup update
          rustup install nightly
          rustup target add wasm32-unknown-unknown

      - name: Install wasmpack
        run: |
          yarn global add wasm-pack

      - name: Build WASM package
        run: |
          pushd isic-playground-glue
          wasm-pack build
          popd

      - name: Build distribution
        run: |
          pushd isic-playground
          yarn install
          yarn build
          popd

      - name: Deploy to Netlify
        run: |
          yarn global add netlify-cli
          netlify deploy --prod -d ./isic-playground/dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
